[package]
name = "weather-landscape"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.65"
console_error_panic_hook = "0.1.7"
reqwest = { version = "0.11.12", features = ["json"] }
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
