name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: AntoineRR/VuePagesAction@add-inputs
      with:
        username: 'AntoineRR'
        reponame: 'weather-landscape'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        directory: './frontend'